### ISSUE TITLE
Cascade Deleting

### ISSUE THREAD

**Issue by LinnierGames** [Breezy-Traveler/Breezy-Traveler-API#102]
# Operations to Cascade
- [x] Delete a hotel (deletes the reference in the trip.hotels array)
- [x] Delete a site (deletes the reference in the trip.sites array)
- [x] Delete a trip (deletes sites and hotels)
- [ ] Delete a user (deletes trips)

**Comment by PhyllisWong** [comment]
Right now there is no way to delete a user. Also, we may want to keep user data.
