### ISSUE TITLE
Use Unsplash to fetch Images

### ISSUE THREAD

**Issue by PhyllisWong** [Breezy-Traveler/Breezy-Traveler-API#8]
https://stackoverflow.com/questions/9182933/is-there-a-ruby-gem-to-use-the-google-images-api

**Comment by LinnierGames** [comment]
The Google API has been giving me trouble such as the following:
<img width="537" alt="screen shot 2018-03-30 at 5 34 24 pm" src="https://user-images.githubusercontent.com/1758210/38157916-9c7bf99e-3440-11e8-8363-8d457cdec101.png">

there are now items found for `searchType: 'image'` but if i search for anything without the `searchType: 'image'` this is what comes back:

<img width="535" alt="screen shot 2018-03-30 at 5 35 11 pm" src="https://user-images.githubusercontent.com/1758210/38157924-c7ce76c6-3440-11e8-98c4-383f6b548de2.png">

So, i'm going to try Unsplash 

**Application page** https://unsplash.com/oauth/applications/23694
**API Docs page** https://unsplash.com/documentation#search-photos

**Comment by PhyllisWong** [comment]
Using Getty Images for the time being
