### ISSUE TITLE
Authorize User Operations

### ISSUE THREAD

**Issue by LinnierGames** [Breezy-Traveler/Breezy-Traveler-API#97]
Prevent users from accessing some of the endpoints.

- [x] Updating another user's trip
> When the user views a published trip, they can send back a put request to modify it even if the trip doesn't belong to the current user. This issue is also noted for the iPhone app; a user cannot send any put requests if they're viewing a trip that is not theirs (isssue [here](google.com)).

**Comment by PhyllisWong** [comment]
linked to issue #99 
fixed with merge
